#!/usr/bin/echo Do not invoke directly.
#===============================================================================
## @file __init__.py
## @brief Initialization for ProtoBuf bindings
## @author Tor Slettnes <tor@slett.net>
#===============================================================================

import core.paths
import sys

## Python code generated by the ProtoBuf compiler goes into the `generated`
## subfolder. However, that code is itself unaware of this fact, so we need
## to append that folder to Python's module search path.
_pythonRoot, _generatedRoot = core.paths.locateDominatingPath('generated')
sys.path.append(_generatedRoot)
