#!/usr/bin/echo Do not invoke directly.
#===============================================================================
## @file __init__.py
## @brief Initialization for ProtoBuf bindings
## @author Tor Slettnes <tor@slett.net>
#===============================================================================

### Modules within package
import cc.core.paths

### Standard Python modules
import sys

## Python code generated by the ProtoBuf compiler goes into the `generated`
## subfolder. However, that code is itself unaware of this fact, so we need
## to append that folder to Python's module search path.
_python_root, _namespace_root = cc.core.paths.locate_dominating_path('cc')
if _namespace_root:
    sys.path.insert(0, str(_namespace_root.joinpath('generated')))
