// -*- c++ -*-
//==============================================================================
/// @file grpc-status.c++
/// @brief gRPC status with detailed error data
/// @author Tor Slettnes
//==============================================================================

#include "grpc-status.h++"
#include "protobuf-event-types.h++"
#include "protobuf-variant-types.h++"
#include "protobuf-standard-types.h++"
#include "protobuf-inline.h++"
#include "platform/symbols.h++"
#include "status/error.h++"
#include "status/exceptions.h++"
#include "logging/logging.h++"

#include "grpc-status-names.gen" // Generated by `create_grpcstatus.py`

namespace cc::grpc
{

    //==========================================================================
    // @class Status

    Status::Status()
    {
    }

    Status::Status(const ::grpc::Status &status)
        : ::grpc::Status(status.error_code(),
                         status.error_message(),
                         status.error_details())
    {
        cc::protobuf::decode(this->details(), this);
    }

    Status::Status(const Status &status)
        : Status(status.status_code(), status)
    {
    }

    Status::Status(const Error &error)
        : Status(This::code_from_error(error), error)
    {
    }

    Status::Status(const cc::protobuf::status::Error &details)
        : Error(
              details.text(),
              cc::protobuf::decoded<core::status::Domain>(details.domain()),
              details.origin(),
              details.code(),
              details.symbol(),
              cc::protobuf::decoded<core::status::Level>(details.level()),
              cc::protobuf::decoded<core::dt::TimePoint>(details.timestamp()),
              cc::protobuf::decoded<core::types::KeyValueMap>(details.attributes())),
          ::grpc::Status(
              This::code_from_error(*this),
              details.text(),
              details.SerializeAsString())
    {
    }

    Status::Status(::grpc::StatusCode status_code,
                   const std::string &text,
                   const cc::protobuf::status::Error &details)
        : Error(
              text,
              cc::protobuf::decoded<core::status::Domain>(details.domain()),
              details.origin(),
              details.code(),
              details.symbol(),
              cc::protobuf::decoded<core::status::Level>(details.level()),
              cc::protobuf::decoded<core::dt::TimePoint>(details.timestamp()),
              cc::protobuf::decoded<core::types::KeyValueMap>(details.attributes())),
          ::grpc::Status(
              status_code,
              text,
              details.SerializeAsString())
    {
    }

    Status::Status(::grpc::StatusCode status_code,
                   const Error &error)
        : Status(status_code,
                 error.text(),
                 error.domain(),
                 error.origin(),
                 error.code(),
                 error.symbol(),
                 error.level(),
                 error.timepoint(),
                 error.attributes())
    {
    }

    Status::Status(::grpc::StatusCode status_code,
                   const std::string &text,
                   core::status::Domain domain,
                   const std::string &origin,
                   Code code,
                   const Symbol &symbol,
                   core::status::Level level,
                   const core::dt::TimePoint &timepoint,
                   const core::types::KeyValueMap &attributes)
        : Error({}, domain, origin, code, symbol, level, timepoint, attributes),
          ::grpc::Status(
              status_code,
              text,
              cc::protobuf::encoded<cc::protobuf::status::Error>(
                  *static_cast<Error *>(this))
                  .SerializeAsString())
    {
    }

    bool Status::equivalent(const Event &other) const noexcept
    {
        if (auto *that = dynamic_cast<const Status*>(&other))
        {
            return Super::equivalent(other) &&
                (this->status_code() == that->status_code());
        }
        else
        {
            return false;
        }
    }

    ::grpc::StatusCode Status::status_code() const noexcept
    {
        return this->error_code();
    }

    std::string Status::status_code_name() const noexcept
    {
        return Status::status_code_name(this->status_code());
    }

    std::string Status::status_code_name(::grpc::StatusCode status_code) noexcept
    {
        try
        {
            return grpc_status_names.at(status_code);
        }
        catch (const std::out_of_range &e)
        {
            return std::to_string(status_code);
        }
    }

    std::string Status::text() const noexcept
    {
        return this->error_message();
    }

    cc::protobuf::status::Error Status::details() const noexcept
    {
        cc::protobuf::status::Error msg;
        msg.ParseFromString(this->error_details());
        return msg;
    };

    std::string Status::class_name() const noexcept
    {
        return TYPE_NAME_BASE(Status);
    }

    std::vector<std::string> Status::field_names() const noexcept
    {
        return This::status_fields();
    }

    std::vector<std::string> Status::status_fields() noexcept
    {
        std::vector<std::string> fields = Error::error_fields();
        fields.insert(fields.begin(), STATUS_FIELD_CODE);
        return fields;
    }

    core::types::Value Status::get_field_as_value(
        const std::string &field_name) const
    {
        if (field_name == STATUS_FIELD_CODE)
        {
            return this->status_code_name();
        }
        else
        {
            return Super::get_field_as_value(field_name);
        }
    }

    ::grpc::StatusCode Status::code_from_error(const core::status::Error &error) noexcept
    {
        switch (error.domain())
        {
        case core::status::Domain::NONE:
            return error.empty()
                       ? ::grpc::StatusCode::OK
                       : ::grpc::StatusCode::UNKNOWN;

        case core::status::Domain::SYSTEM:
        case core::status::Domain::APPLICATION:
            return Status::code_from_errno(error.code());

        case core::status::Domain::SERVICE:
        case core::status::Domain::DEVICE:
        case core::status::Domain::PROCESS:
            return ::grpc::StatusCode::ABORTED;

        default:
            return ::grpc::StatusCode::UNKNOWN;
        }
    }

    ::grpc::StatusCode Status::code_from_errno(int err) noexcept
    {
        switch (static_cast<std::errc>(err))
        {
        case std::errc::operation_canceled:
            return ::grpc::StatusCode::CANCELLED;

        case std::errc::timed_out:
            return ::grpc::StatusCode::DEADLINE_EXCEEDED;

        case std::errc::address_in_use:
        case std::errc::file_exists:
        case std::errc::already_connected:
            return ::grpc::StatusCode::ALREADY_EXISTS;

        case std::errc::operation_not_supported:
            return ::grpc::StatusCode::FAILED_PRECONDITION;

        case std::errc::no_such_file_or_directory:
        case std::errc::no_such_device_or_address:
        case std::errc::no_such_device:
        case std::errc::no_such_process:
            return ::grpc::StatusCode::NOT_FOUND;

        case std::errc::permission_denied:
        case std::errc::operation_not_permitted:
            return ::grpc::StatusCode::PERMISSION_DENIED;

        case std::errc::result_out_of_range:
            return ::grpc::StatusCode::OUT_OF_RANGE;

        case std::errc::file_too_large:
        case std::errc::no_space_on_device:
            return ::grpc::StatusCode::RESOURCE_EXHAUSTED;

        case std::errc::invalid_argument:
        case std::errc::filename_too_long:
        case std::errc::argument_out_of_domain:
        case std::errc::argument_list_too_long:
            return ::grpc::StatusCode::INVALID_ARGUMENT;

        case std::errc::device_or_resource_busy:
        case std::errc::operation_in_progress:
        case std::errc::text_file_busy:
        case std::errc::interrupted:
            return ::grpc::StatusCode::ABORTED;

        case std::errc::io_error:
        case std::errc::resource_unavailable_try_again:
            return ::grpc::StatusCode::UNAVAILABLE;

        default:
            return ::grpc::StatusCode::UNKNOWN;
        }
    }

    void Status::throw_if_error() const
    {
        if (!this->ok())
        {
            Super::throw_if_error();
        }
    }

    std::exception_ptr Status::as_exception_ptr() const
    {
        if ((this->domain() == core::status::Domain::NONE) && !this->ok())
        {
            return this->as_application_error();
        }
        else
        {
            return Super::as_exception_ptr();
        }
    }

    std::exception_ptr Status::as_application_error() const
    {
        switch (this->status_code())
        {
        case ::grpc::StatusCode::CANCELLED:
            return std::make_exception_ptr<core::exception::Cancelled>(*this);

        case ::grpc::StatusCode::DEADLINE_EXCEEDED:
            return std::make_exception_ptr<core::exception::Timeout>(*this);

        case ::grpc::StatusCode::INVALID_ARGUMENT:
            return std::make_exception_ptr<core::exception::InvalidArgument>(*this);

        case ::grpc::StatusCode::OUT_OF_RANGE:
            return std::make_exception_ptr<core::exception::OutOfRange>(*this);

        case ::grpc::StatusCode::FAILED_PRECONDITION:
            return std::make_exception_ptr<core::exception::FailedPrecondition>(*this);

        case ::grpc::StatusCode::NOT_FOUND:
            return std::make_exception_ptr<core::exception::NotFound>(*this);

        case ::grpc::StatusCode::ALREADY_EXISTS:
            return std::make_exception_ptr<core::exception::Duplicate>(*this);

        case ::grpc::StatusCode::PERMISSION_DENIED:
            return std::make_exception_ptr<core::exception::PermissionDenied>(*this);

        case ::grpc::StatusCode::RESOURCE_EXHAUSTED:
            return std::make_exception_ptr<core::exception::ResourceExhausted>(*this);

        case ::grpc::StatusCode::ABORTED:
            return std::make_exception_ptr<core::exception::RuntimeError>(*this);

        case ::grpc::StatusCode::UNAVAILABLE:
            return std::make_exception_ptr<core::exception::Unavailable>(*this);

        default:
            return std::make_exception_ptr<core::exception::UnknownError>(*this);
        }
    }

} // namespace cc::grpc
